
version: 2.1
jobs:
  build-mac:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          name: "update submodules"
          command: "git config --global http.sslverify false && git submodule update --init --recursive"
      - run:
          name: "build"
          command: "make"

workflows:
  build-binaries-workflow:
    jobs:
      - build-mac
